### ISSUE TITLE
Icons do not display

### ISSUE THREAD

**Issue by Node-Ninja** [nitishrajuprety/dynamic_weather_icons#1]
![Screenshot_20200624-124351](https://user-images.githubusercontent.com/8701027/85541595-719ff480-b618-11ea-91b6-63e04f96b4d7.jpg)

Code used: 
`Icon(
                            WeatherIcon.getIcon('wi-owm-day-200'),
                            color: Colors.white,
                            size: 35.0,
                          )`

Tried various icon codes but it is always either blank or with a rectangular block with an X inside

**Comment by nitishrajuprety** [comment]
@Node-Ninja please update to latest version, this problem should be fixed now. Thanks for the feedback and let me know if there is any more issue.
