### ISSUE TITLE
Flutter apk release is not working because of the dynamic library

### ISSUE THREAD

**Issue by mohitbattu** [nitishrajuprety/dynamic_weather_icons#2]
I am getting the following error when I tried to run this command "flutter build apk --release --split-per-abi".
Actually I am using your library to fetch the five days weather forecast icons dynamically.My application is working fine in the debug mode but when i changed it to the release mode the following error has been generated as shown in the picture below
Error Generated:-
![weather-issue](https://user-images.githubusercontent.com/39517972/109116265-e013f400-775d-11eb-883e-a13ba8b0bc2e.png)

  Please, help me to resolve this issue asap!!

**Comment by nitishrajuprety** [comment]
Try building with --no-shrink flag and it should work.
